### ISSUE TITLE
Bionic Health Bonuses Incompatibility

### ISSUE THREAD

**Issue by AnachronisticJam** [Tachyonite/Pawnmorpher#357]
Pawnmorpher locks organ health to vanilla values, preventing mods that add health to organs or limbs from functioning.

See [linked](https://imgur.com/a/0wTh3NS) image for example

**Note:** Issue was identified and tested on the current 1.3.3117 build of Rimworld on Sept. 11, 2021

**To Reproduce**
1. Download
- [Harmony](https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077)
- [HugsLib](https://steamcommunity.com/sharedfiles/filedetails/?id=818773962)
- [Elite Bionics Framework](https://steamcommunity.com/sharedfiles/filedetails/?id=1665403571)
- [Expanded Prosthetics and Organ Engineering 2.4](https://steamcommunity.com/sharedfiles/filedetails/?id=725956940)
- [Internal Armor Plats EPOE](https://steamcommunity.com/sharedfiles/filedetails/?id=2103181887)
- [Humanoid Alien Races](https://steamcommunity.com/sharedfiles/filedetails/?id=839005762)
- [Pawnmorpher](https://steamcommunity.com/sharedfiles/filedetails/?id=1786466855)

2. Launch a new game, new map
- Activate dev mode, build a surgery center, set all pawn skills to 20 for easy surgery
- Spawn "Synthetic Heart" and "Internal Armor Plate"
- Install both into pawn
- Check health values

**Error Log**
No error during, before, or after surgery

**Expected behavior**
The organ health should be at the expected final value, rather than being locked to core values

**Screenshots**
See above [link](https://imgur.com/a/0wTh3NS)

**Additional context**
Final load order:

1. Harmony
2. Core
3. Royalty
4. Ideology
5. HugsLib
6. Elite Bionics
7. EPOE
8. Internal Armor
9. Humanoid Alien Races
10. Pawnmorpher

**Comment by Nerdnub** [comment]
Experiencing a similar issue with Android Tiers (specifically as it relates to the M7 and M8 pawns) that I believe is the same bug. The pawns use the same body parts as other androids, but with a higher baseHealthScale. This bug appears to cause the baseHealthScale to be applied to the max health, but not the current health. Looking through the assembly, I believe this issue is potentially being caused either by the Pawnmorph.BodyUtilities.GetPartNormalizedHealth value always returning 1 (but not greater than 1 because the part isn't considered mutated), or by the Pawnmorph.BodyUtilities.GetPartMaxHealth offset not being calculated correctly.

**Comment by Zeracronius** [comment]
Elite Bionics have patched this incompatibility on their end, so this should be fixed.
