### ISSUE TITLE
Healer mech can cause mutations on animals.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#421]
**Describe the bug**
Healer mech can cause mutations on animals.

**Comment by lelodu87** [comment]
That may not confirm the issue, but when you use the console command "give random mutations" on animals, they indeed get mutatations. They healer and that command may have similar behaviours.

**Comment by lelodu87** [comment]
You cannot administer mutagenic resurecter/healer to animals. So this issue can only happen when you have some mods allowing the use of them (Xenobionic Patcher?).

Let us note we cannot use them on former humans too.

However, it is possible to give animal mutations through console (give random mutations). Fixing this bug is doable this way.
