### ISSUE TITLE
Conversion to Harmony.Patch from annotated patches? (Free Morphs not generating with morphs due to irrelevant annotated-patch failure)

### ISSUE THREAD

**Issue by jtgibson01** [Tachyonite/Pawnmorpher#692]
After disabling any mod that could have possibly affected Page_ConfigureStartingPawns, GenerateInitialHediffs (except for AlienRaces), GeneratePawnInternal and/or TryGeneratePawnInternal, I was still not receiving any morphs upon the new animalmorphs when choosing the Free Morphs scenario.

I went ahead and converted the patch to use a direct Harmony.Patch call in PawnmorphPatches.cs:
```
		try
			{
				harmonyInstance.Patch(
					AccessTools.Method(typeof(PawnGenerator), "GenerateInitialHediffs", new Type[] {typeof(Pawn), typeof(PawnGenerationRequest)}),
					postfix: new HarmonyMethod(typeof(PawnGeneratorPatches.InitialHediffsPatch), nameof(PawnGeneratorPatches.InitialHediffsPatch.Postfix))
					);
			}
			catch (Exception e)
			{
				Log.Error($"Pawnmorpher: encountered {e.GetType().Name} while patching Pawn.GenerateInitialHediffs\n{e}");
			}
```
and commented out the annotated version in PawnGeneratorPatches, and lo and behold **it worked perfectly**.

Baffled, after polling What The Patch, it turned out that the annotated method wasn't even being patched by Harmony.  The cause is evidently if a single annotated Harmony patch fails, all subsequent annotated Harmony patches fail.  As compared, properly encapsulated try-catch Harmony.Patch calls fail safe.

For sake of mod intercompatibility and version agnosticism, would it be unreasonable to move all patches from the annotated versions to the manual patching operations in PawnmorphPatches?

-----

In my case, the transpiler in IsRopeManagedAnimalDefPatch is targetting a vanilla function that's missing, because I'm still running build 3117 via Ludeon's DRM free version (which I discovered was the cause *after* spending all the effort to try to fix the bug ;-)).  (Yes, I own RimWorld on both Steam and direct from Ludeon and can easily prove it.  I just don't trust Valve farther than I can throw them and have no intention of switching to the auto-updated version. =P)

I'm already in the process of updating RimWorld and my RimWorld mods to the new version (blech, might as well just set half of my house on fire), but the major issue is that the annotated patches are a particularly fragile point of failure.  This time it was an easily solved version problem on the user end, but that won't always be the case. =)

**Comment by Zeracronius** [comment]
I will look into what can be done, but the amount of patching means that some options might not be feasible in terms of maintainability.

Version agnosticity for minor versions won't ever be possible however since only major versions are separated in mod, and the mod is distributed on steam workshop specifically for the latest version available there.

It could be a required patch completely changed in an update rather than completely missing and the code then wouldn't be able to work with a previous version at all in the first place.

**Comment by Zeracronius** [comment]
Annotated patch exceptions can be suppressed by adding a finaliser method returning null. (See harmony documentation)
However, even if we suppressed the errors it still wouldn't provide better support or mod compatibility. If the patches aren't applied then the mod won't work.
If we do encounter mod conflicts, then they need to be handled manually from one of the parties involved to ensure compatibility. 
Simply throwing an error in the log and moving on won't really be a good solution, and might even make people think it's fine since it still loaded.

I have talked with the other developers. This mod does a _lot_ of patching, and doing a lot of extra work to make the mod not even work any better or be more compatible is not something we want to do.

**Comment by jtgibson01** [comment]
A couple counter-points:

1. The only thing that failed was the Free Morph generation, which occurred after attempting to patch a function that wasn't there in the 3117 version to begin with -- meaning that intended behaviour was actually degraded by the mod attempting undefined behaviour.  (I was a little surprised, actually, when I compared before-and-after from the list of patched functions reported and it turned out that only that one other method had failed.)
Harmony annotated patches aren't really known quantities in order of evaluation, so it could have been worse, but in this case, if that patch *wasn't* applied then the mod *would* have worked better, heh; it would have been a graceful degradation of behaviour and the mod would have worked perfectly on both 3117 *and* on 3887, with behaviour in 3117 identical to the way it was on the final version for 3117 before that roping behaviour was added.

2. Not even if I did the work?  It'd take me less than around 30 minutes to an hour to move everything to the static constructor method (give or take two days for "buffer time" ;-)).  I'm always in favour of spending the effort to improve the robustness of code when it becomes evident that an existing implementation can fail for some users on a major version.

I did finally suck it up and update to 3887 (which broke more than a few other mods, but that's all sorted), so it's moot anyway if the decision is final,
