### ISSUE TITLE
dependency loop

### ISSUE THREAD

**Issue by johnson1233** [Tachyonite/Pawnmorpher#892]
**Describe the bug**
when pawn morpher is in the same modlist as CE or alpha animals or cooking expanded or etc it wont sort with rimpy and if you ignore it will make loading never end,
*"There are loops of dependencies in your mods list.
Next mods depend on each other:
Loop №1:
sarg.alphaanimals
tachyonite.pawnmorpherpublic
ceteam.combatextended"*

**Mods Involved**
https://rentry.co/b72h4fwy modlist.
**To Reproduce**
have cooking expanded, alpha animals , CE, and humanoid alien races in the same modlist.

**Error Log**
no errors because i cant get past the loading screen in the first place.

**Expected behavior**
mod sorts normally and i can get into the game.

**Screenshots**
none needed.

**Additional context**
i use rimpy sort but this issue only started once i added this mod.

**Comment by Zeracronius** [comment]
Though marked as closed, that could have been an accident, i will just add that this issue has long since been fixed, PM has to be under CE and AA's integration that required it to be below PM was never updated to 1.4.
It has since been removed together with the load order definition months ago, so make sure you are using updated mods.

Rimpy database is known to cache and contain outdated mod metadata.
